image: rambabusaravanan/firebase:latest
stages:
  - build
cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store
    - node_modules/
build site main:
  stage: build
  variables:
    VITE_CI_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  before_script:
    - apk add --no-cache curl
    - curl -fsSL 'https://get.pnpm.io/install.sh' -o /bin/pnpm
    - chmod +x /bin/pnpm
  script:
    - pnpm install
    - pnpm run build
    - firebase use --token $FIREBASE_TOKEN default
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
      - node_modules/
  artifacts:
    paths:
      - dist/
