stages:
- build

build site:
  stage: build
  image: rambabusaravanan/firebase:latest
  variables:
    VITE_CI_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
    FIREBASE_TOKEN: $1//0cywBikIT4orsCgYIARAAGAwSNwF-L9IryHq6t8Brb66KCigNBlou58SSOkKwj5G5_gXhpX7MhiXGeM_FurSXUdYpcQXhN5hIMCA
  before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store
  script:
  - pnpm install
  - pnpm run build
  - firebase use --token $FIREBASE_TOKEN default
  - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
  cache:
    key:
      files:
      - pnpm-lock.yaml
    paths:
    - .pnpm-store
    - node_modules/
  artifacts:
    paths:
    - dist/
